255-Shared-Data-Management-WIP
FraunhoferISST/DataspaceConnector pull request #262
Opened 2021-05-19 08:43 UTC by goekhanKahriman

This is the first state of shared data management. The model classes have been extended, services for the models have been created and repositories have been added.

The current state cannot be started, because in the class **EntityLinkerService.java**, the annotation `@Service` at **RouteEndEndpointLinker** and **RouteStartEndpointLinker** leads to the following error:

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.dataspaceconnector.repositories.BaseEntityRepository<io.dataspaceconnector.model.Endpoint>' available: expected at least 1 bean which qualifies as autowire candidate.`

`ERROR - \r\n\r\n***************************\r\nAPPLICATION FAILED TO START\r\n***************************\r\n\r\nDescription:\r\n\r\nField repository in io.dataspaceconnector.services.resources.BaseEntityService required a bean of type 'io.dataspaceconnector.repositories.BaseEntityRepository' that could not be found.`

2021-05-27 13:57 UTC, juliapampus commented
just noticed: could you please stick to our contribution guidelines? https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/develop/CONTRIBUTING.md#commits

2021-05-31 05:21 UTC, brianjahnke commented
You have lots of files without any changes, only the order of the includes is changing. Is there a reason for this?

2021-06-01 08:02 UTC, goekhanKahriman commented
> You have lots of files without any changes, only the order of the includes is changing. Is there a reason for this?

It could be because I have used the optimize imports functionality from the intellij development environment.

2021-06-01 08:03 UTC, goekhanKahriman commented
> just noticed: could you please stick to our contribution guidelines? https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/develop/CONTRIBUTING.md#commits

I will consider it in the next commits

2021-06-02 05:35 UTC, brianjahnke commented
Still a lot of classes with only style changes. Please revert those. 

Maybe some packages would help sorting this rather big number of entities? @tmberthold

2021-06-02 12:02 UTC, brianjahnke requested changes
First iteration.

Not sure if all the relations are initialized in the factories and if all links are created in views.

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/configurations/ConfigmanagerController.java
> +public final class ConfigmanagerController {
Split this up into multiple classes? e.g. extract Broker.

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/ContractRequestMessageController.java
> +                            | MessageResponseException e) {
Revert

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/resources/ResourceControllers.java
> +                            queryInput));
Revert

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/resources/ResourceNotFoundExceptionHandler.java
>  import org.springframework.core.annotation.Order;
Revert

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpoint.java
> +public class AppEndpoint extends Endpoint {
Have you checked if this delete does work with the parent table?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpoint.java
> +    private int appEndpointPort;
even negativ numbers? maybe unsigned?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpointFactory.java
> +
remove empty line

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpointFactory.java
> +    public static final String DEFAULT_STRING = "unknown";
Why DEFAULT_STRING and not DEFAULT_MEDIATYPE?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpointFactory.java
> +        update(appEndpoint, desc);
Is the update function not called in the parent? Maybe a duplicated update call?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpointType.java
> +     * Endpoint is used to get app health / lifecycle status.
Which one health or lifecycle?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppEndpointType.java
> +     * Endpoint is used for usage policy / usage control related scenarios.
Which one?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppFactory.java
> +        return false;
Is this right? @tmberthold

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppStoreDesc.java
> +    private RegisterStatus registerStatus;
Maybe the enum type should also be called RegistrationStatus?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AppStoreFactory.java
> +        return false;
Is this correct? @tmberthold

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/Authentication.java
> +public class Authentication extends AbstractEntity {
Maybe authentification data should be hard deleted? Not sure

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/Authentication.java
> +    private String username;
Do we need the username and password as plain text or would a hash also work?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AuthenticationFactory.java
> +    private boolean updatePassword(final Authentication auth, final String password) {
Should the default value really be "username"? If so move it into a constant

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/AuthenticationFactory.java
> +        final var newPassword = MetadataUtils.updateString(auth.getPassword(), password,
see password

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ClearingHouseDesc.java
> +public class ClearingHouseDesc extends AbstractDescription<ClearingHouse> {
Please make sure atleast all *Desc classes have equals and hash functions and are symetric

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ConfigurationFactory.java
> +                MetadataUtils.updateString(config.getKeyStorePassword(), keyStorePassword,
Move default values into constants

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ConnectorDeployMode.java
> +    PRODUCTIVE_DEPLOYMENT("Productive Deployment"),
drop _DEPLOYMENT

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ConnectorFactory.java
> +                DEFAULT_STRING);
DEFAULT_STRING -> DEFAULT_TITLE. clearer intent

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ConnectorFactory.java
> +                DEFAULT_URI);
DEFAULT_ACCESS_URI

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ConnectorStatus.java
> +    CONNECTOR_BADLY_CONFIGURED("Connector badly configured"),
How to you identify if a connector is broken or badly configured? 

I suggest a better naming for all states. E.g. like spring boot actuators
ONLINE -> ACCEPTING_TRAFFIC
OFFLINE -> REFUSING_TRAFFIC

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/DataSourceFactory.java
> +    private static final String DEFAULT_STRING = "unknown";
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/DataSourceType.java
> +    DATABASE("Database"),
The types of datasource seems quite random? What is the logic here? e.g. File <-> Directory

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/DeployMethod.java
> +    KAFKA("Kafka"),
Why have deploy methods that do not exist?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/EndpointDesc.java
> +    private String inboundPath;
URI or URL, String seems too generic

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/EndpointDesc.java
> +    private String outboundPath;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/EndpointFactory.java
> +    private static final String DEFAULT_STRING = "default";
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/EndpointFactory.java
> +                outboundPath, DEFAULT_STRING);
Are the defaults for input and output always identically?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/EndpointType.java
> +    GENERIC_ENDPOINT("Generic endpoint"),
drop _ENDPOINT

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/GenericEndpoint.java
> +public class GenericEndpoint extends Endpoint {
have you tested if the soft delete worked?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/GenericEndpoint.java
> +    private String absolutePath;
URL? see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/GenericEndpointDesc.java
> +    private String absolutePath;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/GenericEndpointFactory.java
> +    private static final String DEFAULT_PATH = "https://path";
URL? see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/GenericEndpointFactory.java
> +        update(genericEndpoint, desc);
createInternal should not call update?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdentityProvider.java
> +public class IdentityProvider extends AbstractEntity {
Does this class already exist but is named differently? Feels like i have seen something identically, Connector maybe?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdentityProviderDesc.java
> +    private URI accessUrl;
Its called URL but is an URI, which one is needed?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdentityProviderFactory.java
> +    private static final String DEFAULT_STRING = "unknown";
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdentityProviderFactory.java
> +    private static final URI DEFAULT_URI = URI.create("https://identityprovider.com");
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdentityProviderFactory.java
> +    private static final String DEFAULT_STRING = "unknown";
Also why are they not public? Maybe it could be needed?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdsEndpoint.java
> +public class IdsEndpoint extends Endpoint {
@table, see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdsEndpoint.java
> +    private URI accessURL;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdsEndpointDesc.java
> +    private URI accessURL;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdsEndpointFactory.java
> +    private static final URI DEFAULT_URI = URI.create("https://path");
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/IdsEndpointFactory.java
> +        update(idsEndpoint, desc);
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/LogLevel.java
> +    DEBUG_LEVEL_LOGGING("Debug Level Logging"),
drop _LOGGING

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/LogLevel.java
> +    DEBUG_LEVEL_LOGGING("Debug Level Logging"),
Why the deviating from common Logging Levels? Off, Trace, Debug, Info, Warn, Error, Fail

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/Proxy.java
> +    private List<URI> noProxyURI;
No Proxy <-> Proxy Uri? What does the noProxyUri do?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ProxyDesc.java
> +    private List<URI> noProxyURI;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ProxyFactory.java
> +    private static final URI DEFAULT_URI = URI.create("https://access");
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ProxyFactory.java
> +    public static final List<URI> DEFAULT_URI_LIST = List.of(URI.create("https://noproxylist"));
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ProxyFactory.java
> +        proxy.setAuthentication(null);
noProxyUri list not initialized?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/RegisterStatus.java
> +    UNREGISTERED("Unregistered");
Why the unregisted state? what is the difference between not been registered and unregistered?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/Route.java
> +    @OneToOne
@tmberthold I do not understand why there is difference between the generic and the ids endpoints? What makes them special (except the protocol)?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/RouteDesc.java
> +    private String routeConfiguration;
Can this be made more specific?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/RouteFactory.java
> +    private static final String DEFAULT_STRING = "Default configuration";
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/utils/ListUriConverter.java
> +
remove empty line

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/utils/ListUriConverter.java
> +    public List<URI> convertToEntityAttribute(final String joinedList) {
Why not @ElementCollection on the problematic field?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/repositories/ConfigurationRepository.java
> +public interface ConfigurationRepository extends BaseEntityRepository<Configuration> {
Do any of the repositories need remote uris?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getAuthentication());
Why not directly implement it as list or as single object? Could lead to problems down the line

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getAuthentication());
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getStartGenericEndpoint());
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getEndGenericEndpoint());
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getStartIdsEndpoint());
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getEndIdsEndpoint());
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/resources/RetrievalInformation.java
>  /**
revert

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/ContractRuleFactory.java
> +
revert

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/utils/ErrorMessages.java
>      /**
missing empty line after AUTH_NULL

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/utils/MetadataUtils.java
>          return Optional.empty();
integer cannot be null

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/utils/MetadataUtils.java
> +        return result;
why not in one line?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/AppEndpointView.java
> +    private URI accessURL;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/AppEndpointView.java
> +    private int appEndpointPort;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/AppStoreView.java
> +    private URI accessUrl;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/AppStoreViewAssembler.java
> +        final var appLink = WebMvcLinkBuilder
You can import linkTo staticlly and drop the WebMvcLinkBuilder. (Multiple classes)

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/AuthenticationView.java
> +@Relation(collectionRelation = "authentications", itemRelation = "authentication")
Weren't the authentications all one to one relations?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/BrokerView.java
> +    private URI accessUrl;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/BrokerViewAssembler.java
> +        final var offeredResourcesLink = WebMvcLinkBuilder
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/ClearingHouseView.java
> +    private URI accessUrl;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/ConfigurationView.java
> +    private String keyStore;
Maybe URL or URI?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/DataSourceView.java
> +    private String relativePath;
Maybe URL?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/DataSourceView.java
> +    private Authentication authentication;
Shoudn't this be a view?

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/DataSourceViewAssembler.java
> +        final var genericEndpointsLink = WebMvcLinkBuilder
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/GenericEndpointView.java
> +    private String absolutePath;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/IdentityProviderView.java
> +    private URI accessUrl;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/IdsEndpointView.java
> +    private URI accessURL;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/ProxyView.java
> +    private List<URI> noProxyURI;
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/ProxyViewAssembler.java
> +                ProxyView.class);
On some of these the formatting seems strange

2021-06-02 12:02 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/view/RouteViewAssembler.java
> +        final var subroutes = WebMvcLinkBuilder
see before

2021-06-02 12:02 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/services/resources/CatalogRequestedResourceLinkerTest.java
> +import java.util.UUID;
revert

2021-06-02 12:02 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/services/resources/CatalogServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
revert

2021-06-02 12:02 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/utils/PatternUtilsTest.java
> +
revert

2021-06-07 10:10 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/controller/configurations/ConfigmanagerController.java
> +public final class ConfigmanagerController {
splitted ConfigmanagerController into multiple controller classes

2021-06-07 10:16 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/controller/messages/ContractRequestMessageController.java
> +                            | MessageResponseException e) {
reverted

2021-06-07 10:16 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/controller/resources/ResourceControllers.java
> +                            queryInput));
reverted

2021-06-07 10:18 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/controller/resources/ResourceNotFoundExceptionHandler.java
>  import org.springframework.core.annotation.Order;
reverted

2021-06-07 10:19 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpoint.java
> +public class AppEndpoint extends Endpoint {
it will be tested

2021-06-07 10:19 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpoint.java
> +    private int appEndpointPort;
only positive numbers for ports are allowed

2021-06-07 10:23 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpointFactory.java
> +    public static final String DEFAULT_STRING = "unknown";
created DEFAULT_MEDIATYPE

2021-06-07 10:23 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpointFactory.java
> +
removed empty line

2021-06-07 10:28 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpointFactory.java
> +        update(appEndpoint, desc);
the update method here updates the attributes that are specific to appendpoints
do you think this is not correct implemented @brianjahnke ?

2021-06-07 10:30 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpointType.java
> +     * Endpoint is used to get app health / lifecycle status.
is now unique

2021-06-07 10:30 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppEndpointType.java
> +     * Endpoint is used for usage policy / usage control related scenarios.
is now unique

2021-06-07 10:31 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppFactory.java
> +        return false;
cannot be answered at this time, the exact implementation and context will be seen in the future

2021-06-07 10:33 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppStoreDesc.java
> +    private RegisterStatus registerStatus;
renamed to RegistrationStatus

2021-06-07 10:34 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AppStoreFactory.java
> +        return false;
cannot be answered at this time, the exact implementation and context will be seen in the future

2021-06-07 10:34 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/Authentication.java
> +public class Authentication extends AbstractEntity {
what do you think @tmberthold ?

2021-06-07 10:35 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/Authentication.java
> +    private String username;
I will leave it like this for now

2021-06-07 10:38 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AuthenticationFactory.java
> +    private boolean updatePassword(final Authentication auth, final String password) {
created constant

2021-06-07 10:39 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/AuthenticationFactory.java
> +        final var newPassword = MetadataUtils.updateString(auth.getPassword(), password,
created constant

2021-06-07 10:49 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ConfigurationFactory.java
> +                MetadataUtils.updateString(config.getKeyStorePassword(), keyStorePassword,
created constants

2021-06-07 10:53 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ConnectorDeployMode.java
> +    PRODUCTIVE_DEPLOYMENT("Productive Deployment"),
dropped

2021-06-07 10:53 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ConnectorFactory.java
> +                DEFAULT_STRING);
changed

2021-06-07 10:54 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ConnectorFactory.java
> +                DEFAULT_URI);
changed

2021-06-07 10:55 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ConnectorStatus.java
> +    CONNECTOR_BADLY_CONFIGURED("Connector badly configured"),
I have taken the descriptions from the infomodel

2021-06-07 10:55 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ContractRuleFactory.java
> +
reverted

2021-06-07 10:57 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/DataSourceType.java
> +    DATABASE("Database"),
what do you think about it @tmberthold ?

2021-06-07 10:58 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/DeployMethod.java
> +    KAFKA("Kafka"),
these are enums that have been determined in the course of route development

2021-06-07 10:59 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/EndpointDesc.java
> +    private String inboundPath;
@tmberthold what do you think about it ?

2021-06-07 10:59 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/EndpointDesc.java
> +    private String outboundPath;
@tmberthold ?

2021-06-07 11:03 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/EndpointFactory.java
> +                outboundPath, DEFAULT_STRING);
separated

2021-06-07 11:03 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/EndpointFactory.java
> +    private static final String DEFAULT_STRING = "default";
changed

2021-06-07 11:03 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/EndpointType.java
> +    GENERIC_ENDPOINT("Generic endpoint"),
dropped

2021-06-07 11:04 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/GenericEndpoint.java
> +public class GenericEndpoint extends Endpoint {
it will be deleted

2021-06-07 11:04 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/GenericEndpoint.java
> +    private String absolutePath;
@tmberthold ?

2021-06-07 11:04 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/GenericEndpointDesc.java
> +    private String absolutePath;
@tmberthold ?

2021-06-07 11:04 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/GenericEndpointFactory.java
> +    private static final String DEFAULT_PATH = "https://path";
@tmberthold ?

2021-06-07 11:05 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/GenericEndpointFactory.java
> +        update(genericEndpoint, desc);
it calls update because generic endpoint hast more attributes than the super class endpoint.
Do you think that this implemenation make problems @brianjahnke ?

2021-06-07 11:07 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdentityProvider.java
> +public class IdentityProvider extends AbstractEntity {
ClearingHouse, IdentityProvider, Connector have at the time all the same structure. More information about the context is needed and due the fact it will be leaved for this time

2021-06-07 11:08 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdentityProviderDesc.java
> +    private URI accessUrl;
it is calles accessUrl but specified as URI, like in infomodel

2021-06-07 11:09 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdentityProviderFactory.java
> +    private static final URI DEFAULT_URI = URI.create("https://identityprovider.com");
changed

2021-06-07 11:10 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdentityProviderFactory.java
> +    private static final String DEFAULT_STRING = "unknown";
changed

2021-06-07 11:10 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdsEndpoint.java
> +public class IdsEndpoint extends Endpoint {
it will be tested

2021-06-07 11:10 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdsEndpoint.java
> +    private URI accessURL;
implemented as in infomodel

2021-06-07 11:10 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdsEndpointDesc.java
> +    private URI accessURL;
implemented as in infomodel

2021-06-07 11:11 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdsEndpointFactory.java
> +    private static final URI DEFAULT_URI = URI.create("https://path");
changed

2021-06-07 11:12 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/IdsEndpointFactory.java
> +        update(idsEndpoint, desc);
see the comments for appendpoint factory and genericendpoint factory

2021-06-07 11:12 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/LogLevel.java
> +    DEBUG_LEVEL_LOGGING("Debug Level Logging"),
dropped

2021-06-07 11:13 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/Proxy.java
> +    private List<URI> noProxyURI;
URLs that should be excluded from proxying

2021-06-07 11:14 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ProxyDesc.java
> +    private List<URI> noProxyURI;
URLs that should be excluded from proxying

2021-06-07 11:15 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ProxyFactory.java
> +    private static final URI DEFAULT_URI = URI.create("https://access");
see comments before

2021-06-07 11:15 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ProxyFactory.java
> +    public static final List<URI> DEFAULT_URI_LIST = List.of(URI.create("https://noproxylist"));
see comments before

2021-06-07 11:16 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/ProxyFactory.java
> +        proxy.setAuthentication(null);
initialized now with empty list

2021-06-07 11:16 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/RegisterStatus.java
> +    UNREGISTERED("Unregistered");
@tmberthold can you answer this question maybe ?

2021-06-07 11:17 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/RouteDesc.java
> +    private String routeConfiguration;
the context knowledge is currently missing, what dou you think @tmberthold ?

2021-06-07 11:34 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/RouteFactory.java
> +    private static final String DEFAULT_STRING = "Default configuration";
changed

2021-06-07 11:35 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/utils/ListUriConverter.java
> +
removed

2021-06-07 11:36 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/utils/ListUriConverter.java
> +    public List<URI> convertToEntityAttribute(final String joinedList) {
for now it has no reason, can be discussed

2021-06-07 11:37 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/repositories/ConfigurationRepository.java
> +public interface ConfigurationRepository extends BaseEntityRepository<Configuration> {
can not answer this quesiton, you maybe @tmberthold ?

2021-06-07 11:38 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getAuthentication());
this could possibly be, must be observed and tested

2021-06-07 11:39 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getAuthentication());
this could possibly be, must be observed and tested

2021-06-07 11:39 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getStartGenericEndpoint());
this could possibly be, must be observed and tested

2021-06-07 11:39 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getEndGenericEndpoint());
this could possibly be, must be observed and tested

2021-06-07 11:39 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getStartIdsEndpoint());
this could possibly be, must be observed and tested

2021-06-07 11:39 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/configuration/EntityLinkerService.java
> +            return List.of(owner.getEndIdsEndpoint());
this could possibly be, must be observed and tested

2021-06-07 11:40 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/services/resources/RetrievalInformation.java
>  /**
reverted

2021-06-07 11:40 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/utils/ErrorMessages.java
>      /**
inserted

2021-06-07 11:47 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/utils/MetadataUtils.java
>          return Optional.empty();
fixed

2021-06-07 11:48 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/utils/MetadataUtils.java
> +        return result;
changed

2021-06-07 11:48 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/AppEndpointView.java
> +    private URI accessURL;
see before comments

2021-06-07 11:48 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/AppEndpointView.java
> +    private int appEndpointPort;
see before comments

2021-06-07 11:48 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/AppStoreView.java
> +    private URI accessUrl;
see before comments

2021-06-07 11:52 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/AppStoreViewAssembler.java
> +        final var appLink = WebMvcLinkBuilder
changed

2021-06-07 11:53 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/AuthenticationView.java
> +@Relation(collectionRelation = "authentications", itemRelation = "authentication")
yes of courese, collectionrelation removed

2021-06-07 11:54 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/BrokerView.java
> +    private URI accessUrl;
see comments before

2021-06-07 11:57 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/BrokerViewAssembler.java
> +        final var offeredResourcesLink = WebMvcLinkBuilder
changed

2021-06-07 11:57 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/ClearingHouseView.java
> +    private URI accessUrl;
see comments before

2021-06-07 11:58 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/ConfigurationView.java
> +    private String keyStore;
it will be discussed

2021-06-07 11:58 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/DataSourceView.java
> +    private String relativePath;
it will be discussed

2021-06-07 12:00 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/DataSourceView.java
> +    private Authentication authentication;
Yes exactly, but this should also be displayed with the data source

2021-06-07 12:01 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/GenericEndpointView.java
> +    private String absolutePath;
see comments before

2021-06-07 12:01 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/IdentityProviderView.java
> +    private URI accessUrl;
see comments before

2021-06-07 12:01 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/IdsEndpointView.java
> +    private URI accessURL;
see comments before

2021-06-07 12:02 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/ProxyView.java
> +    private List<URI> noProxyURI;
see comments before

2021-06-07 12:02 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/ProxyViewAssembler.java
> +                ProxyView.class);
changed

2021-06-07 12:03 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/view/RouteViewAssembler.java
> +        final var subroutes = WebMvcLinkBuilder
changed

2021-06-07 12:04 UTC, goekhanKahriman commented on src/test/java/io/dataspaceconnector/services/resources/CatalogRequestedResourceLinkerTest.java
> +import java.util.UUID;
reverted

2021-06-07 12:05 UTC, goekhanKahriman commented on src/test/java/io/dataspaceconnector/utils/PatternUtilsTest.java
> +
reverted

2021-06-28 08:17 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/appstore/AppStore.java
> +    private URI name;
accessUrl?

2021-06-28 08:17 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/appstore/AppStoreDesc.java
> +    private URI name;
accessUrl?

2021-06-28 08:17 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/appstore/AppStoreFactory.java
> +    private boolean updateName(final AppStore appStore, final URI name) {
updateAccessUrl?

2021-06-28 08:26 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/appstore/AppStore.java
> +    private RegistrationStatus status;
RegistrationStatus for an AppStore? Is this really an existing feature?

2021-06-28 08:27 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/appstore/AppStore.java
> +    private URI name;
Not really happy with the name accessUrl. I mean its not an URL its an URI. Also why should the type be encoded into the field name?

2021-06-28 08:27 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/appstore/AppStoreDesc.java
> +    private URI name;
se before

2021-06-28 08:27 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/appstore/AppStoreFactory.java
> +    private boolean updateName(final AppStore appStore, final URI name) {
Its named after the field.

2021-06-28 08:28 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/appstore/AppStore.java
> +    private RegistrationStatus status;
Dont think so. Getting rid of it.

2021-06-28 08:30 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/appstore/AppStore.java
> +    private URI name;
Have looked before into the Broker, it's called accessUrl over there, that's why I'm asking.

2021-06-28 08:44 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/appstore/AppStore.java
> +    private URI name;
That is another todo, a bit too much duplicating ^^

2021-06-29 08:18 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/clearinghouse/ClearingHouse.java
> +    private RegistrationStatus status;
Don't think there is a registration for the ClearingHouse, or am I wrong? Logs in CH are bound to so-called processes and "Processes can be created by any IDS connector with a valid DAT, who becomes the owner of the process.". It doesn't sound like registration is required there in advance.

An interesting following question for the CH would be, whether all connectors can query all log histories of all other connectors or only those for which they are the "owner" (-> Query all messages of a process).

Specification: https://github.com/International-Data-Spaces-Association/IDS-G-pre/blob/clearinghouse/Components/ClearingHouse/README.md

2021-06-29 08:27 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/clearinghouse/ClearingHouse.java
> +}
Additional Question: I don't know if the CH process-IDs that were created at the Clearing-House for the logs send to the CH can already be saved in this data storage, because you will have to be able to remember them somehow. Sorry if I just didn't see it.

2021-06-29 10:16 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/apps/AppType.java
> +public enum AppType {
SmartDataApp, SystemAdapter, OrchestrationApp? (all of type DataApp)

2021-06-29 12:03 UTC, ob-silva commented on src/main/java/io/dataspaceconnector/model/base/AbstractFactory.java
> +    protected abstract T initializeEntity(D desc);
I realized that the desc parameter of the intializeEntity Method isn't used in most (if not all) classes that override the method.
For instance, in AgreementFactory, ClearingHouseFactory and other classes desc isn't used in initializeEntity, only in updateEntity. Is this expected or am I missing something?

2021-06-30 13:09 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/base/AbstractFactory.java
> +    protected abstract T initializeEntity(D desc);
This was originally the createInternal function, which is just the type specific create function without input validation. But the internal part of the naming is just bad. So the named changed to initializedEntity, maybe I will change it again to initEntity. The desc Parameter will be dropped if no use case exists, where this information is needed. (Maybe RequestedResources?)

2021-07-01 09:03 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/app/App.java
> +public class App extends NamedEntity {
The following is the information that describes an app as metadata according to the specification of an ids:AppResource ("App" in our understanding):
- ids:title e.g. "DataProcessingApp"
- ids:description e.g. "data app for processing data."
- ids:keyword e.g. "data", "processing", "fit"
- ids:customLicense e.g. <https://www.gnu.org/licenses/gpl-3.0-standalone.html>
- ids:resourceEndpoint with info about the ids:ConnectorEndpoint (ids:endpointInformation, ids:endpointDocumentation, ids:accessURL)
- ids:representation with infos on where to find the registry, app-endpoints, appEnvironmentVariables...

Full specification: 2.4 App Metadata Representation https://industrialdataspace.jiveon.com/docs/DOC-2604

Can we already store this data, which the AppStore will provide to the Connector in an IDS message, in the database?

2021-07-01 10:44 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/app/App.java
> +public class App extends NamedEntity {
With the current state of the app entity, information such as title, description, startEndpoint, and lastEndpoint can be captured.

2021-07-01 11:37 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/app/App.java
> +public class App extends NamedEntity {
One of the most important infos for our cm-backend would be the registry-info, where to docker pull the app from (image), definitely need to save that info as well.

2021-07-01 11:58 UTC, goekhanKahriman commented on src/main/java/io/dataspaceconnector/model/app/App.java
> +public class App extends NamedEntity {
This information will be included to the app model

2021-07-02 11:54 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/view/BrokerView.java
> +public class BrokerView extends RepresentationModel<BrokerView> {
_description_ missing in view?

2021-07-06 09:51 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/services/messages/GlobalMessageService.java
> +    private final @NotNull BrokerRepository brokerRepository;
Tests now throw error messages:
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'globalMessageService': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.dataspaceconnector.repositories.BrokerRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.dataspaceconnector.repositories.BrokerRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

2021-07-06 09:57 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/services/messages/GlobalMessageService.java
> +    private final @NotNull BrokerRepository brokerRepository;
added MockBeans to MockBean

2021-07-14 11:22 UTC, tmberthold commented
io.dataspaceconnector.camel.errorhandler.DeadLetterChannel needs to be adjusted.

Since the CM part is now part of the Dataspace Connector itself, Camel no longer needs/cannot call a ConfigManager API for route error logging.

2021-07-18 08:30 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/model/configuration/Configuration.java
> +    private boolean active;
Must be adjusted: @Column(unique = true) in combination with boolean only allows a maximum of 2 entries (one with true, one with false as value). The check that there must be only one active config must be implemented differently. (Other table/table-entry somewhere pointing to the active config from outside?)

2021-07-18 10:15 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/model/configuration/Configuration.java
> +    private boolean active;
Has already been fixed

2021-07-20 21:05 UTC, juliapampus approved these changes

2021-07-20 21:06 UTC, brianjahnke approved these changes

2021-07-20 21:06 UTC, merged