WIP: 294-ids-messaging-services-integration
FraunhoferISST/DataspaceConnector pull request #306
Opened 2021-06-02 13:45 UTC by renebrinkhege

2021-06-09 12:41 UTC, brianjahnke reviewed
Resolve the todos

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/config/DapsTokenValidator.java
> +                log.warn("The Connector is missing a Cert Extension exception=({})]", e.getMessage());
The Connector is missing a Cert Extension exception=({})]

Full qualified name for Cert
Wrong exception format

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/config/DapsTokenValidator.java
> +            };
Remove ";"

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/ConnectorUnavailableMessageController.java
> +            //TODO: as the Messaging services added  DapsTokenManagerException, ClaimsException and MultipartParseException as ne Exceptions, check if a new type of Response Message is needed
Resolve TODO?

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/ConnectorUnavailableMessageController.java
> +            //TODO: as the Messaging services added  DapsTokenManagerException, ClaimsException and MultipartParseException as ne Exceptions, check if a new type of Response Message is needed
Do we really need to address NPE?

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/ConnectorApplication.java
> +    //"de.fraunhofer.isst.ids.framework.messaging",
Remove out commented stuff

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/ConnectorUpdateMessageController.java
> +            //TODO: as the Messaging services added  DapsTokenManagerException, ClaimsException and MultipartParseException as ne Eceptions, check if a new type of Response Message is needed
see before

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/QueryMessageController.java
> +            // TODO: should all exceptions be handled this way or should a differentiation be made?
see before

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/QueryMessageController.java
> +                String responseAsString = response.getPayload().get();
String -> final var

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/ResourceUnavailableMessageController.java
> +            // TODO: should all exceptions be handled this way or should a differentiation be made?
see before

2021-06-09 12:41 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/messages/ResourceUpdateMessageController.java
> +            // TODO: should all exceptions be handled this way or should a differentiation be made?
see before

2021-06-09 12:49 UTC, brianjahnke requested changes

2021-06-09 12:49 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/ids/DeserializationService.java
> +        } catch (IOException | RiotException e) {
RiotException? Has this been added?

2021-06-09 12:49 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/services/messages/types/ContractRequestService.java
> +//import static de.fraunhofer.isst.ids.framework.util.IDSUtils.getGregorianNow;
Remove commented out code

2021-06-09 12:49 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/controller/messages/QueryMessageControllerTest.java
> +import de.fraunhofer.iais.eis.*;
No star imports, please narrow down the scope

2021-06-10 10:02 UTC, renebrinkhege commented on src/main/java/io/dataspaceconnector/services/ids/DeserializationService.java
> +        } catch (IOException | RiotException e) {
If the RiotException does not get handled the ResourceUpdateMessageHandlerTest fails

2021-07-01 11:44 UTC, juliapampus submitted a review, later dismissed

2021-07-01 12:12 UTC, brianjahnke requested changes

2021-07-01 12:12 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/bootstrap/BootstrapConfigurationTest.java
> +//
delete?

2021-07-01 12:12 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/filter/httptracing/HttpTraceFilterTest.java
> +//        final var requestBody = customServletIS.newInstance("BODY".getBytes(StandardCharsets
delete?

2021-07-01 12:12 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/model/ContractFactoryTest.java
> +//        final var initialEndTime = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss").parse
delete?

2021-07-01 12:12 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/services/ids/IdsCatalogBuilderTest.java
> +        ;
";" ?

2021-07-01 12:12 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/controller/PolicyRestrictionExceptionHandlerTest.java
> +    private final PolicyRestrictionExceptionHandler handler =
dont make this final, not sure if this will clash with mockito tests

2021-07-01 15:46 UTC, juliapampus submitted a review, later dismissed

2021-07-02 13:09 UTC, juliapampus approved these changes

2021-07-02 13:34 UTC, brianjahnke approved these changes

2021-07-02 13:35 UTC, merged