Chore: Log ArtifactRequest and ArtifactResponse Messages
FraunhoferISST/DataspaceConnector pull request #417
Opened 2021-07-13 08:11 UTC by hqarawlus

Improved IDS ClearingHouse logging functionality.

Changes:
* New camel Clearing House processor to log outgoing messages in an IDS-CH
* Adjusted logging of contract agreements to send agreement ID along with the IDS LogMessage as path variable. This will be used in the IDS-CH as a Process ID.

2021-07-15 11:14 UTC, brianjahnke requested changes

2021-07-15 11:14 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/message/type/ArtifactRequestService.java
> +        var message = new ArtifactRequestMessageBuilder()
final?

2021-07-15 11:14 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/message/type/ArtifactRequestService.java
> +        var header = deserializer.getResponseMessage(response.get("header"));
final?

2021-07-15 11:14 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/usagecontrol/PolicyExecutionService.java
> +            if (!clearingHouse.equals(URI.create(""))) {
Is there an equivalent like clearingHouse.isEmpty() ? So that the URI.create("") can be avoided?

2021-07-15 11:14 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/usagecontrol/PolicyExecutionService.java
> +                var recipient = new URI(clearingHouse + agreementUUID.toString());
Is the leading "/" garanteed for "clearingHouse + "?

2021-07-15 13:29 UTC, hqarawlus commented on src/main/java/io/dataspaceconnector/service/usagecontrol/PolicyExecutionService.java
> +            if (!clearingHouse.equals(URI.create(""))) {
Class `java.net.URI` does not have the `isEmpty()` method

2021-07-15 13:29 UTC, hqarawlus commented on src/main/java/io/dataspaceconnector/service/usagecontrol/PolicyExecutionService.java
> +            if (!clearingHouse.equals(URI.create(""))) {
The closest thing I found that can be done here was `clearingHouse.equals(URI.Empty)`

2021-07-17 10:32 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/usagecontrol/PolicyExecutionService.java
> +            if (!clearingHouse.equals(URI.create(""))) {
Changed it.

2021-07-18 13:23 UTC, brianjahnke approved these changes

2021-07-18 13:23 UTC, merged