feat: api provides information about dsc version update is available
FraunhoferISST/DataspaceConnector pull request #581
Opened 2021-09-13 11:35 UTC by goekhanKahriman

2021-09-15 13:51 UTC, tmberthold commented
API return if update available (200 + info):

![image](https://user-images.githubusercontent.com/75306992/133445785-bab903a9-1549-481d-9e7b-7772959972fc.png)

API return if no update available (204 no_content):

![image](https://user-images.githubusercontent.com/75306992/133445862-2dc2ddc3-ee32-447b-bce0-5edc01b2a22d.png)

2021-09-16 06:34 UTC, brianjahnke requested changes

2021-09-16 06:34 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
> +            return ResponseEntity.badRequest().body("Failed to determine if a project"
Why BadRequest and not something like Bad Gateway?

2021-09-16 06:34 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +            response = new ResponseEntity<>(latestData.toString(), HttpStatus.OK);
Services in the DSC do not build the ResponseEntities.
The DSC tends to return json objects. It makes the responses extensible. e.g. 
```
{
  "currentVersion": "x.x.x",
  "latestVersion": "x.x.x",
  "updateAvailable": true|false
}
```
Also this type of response should simplify the responses, would do you think?

2021-09-16 06:34 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        builder.get();
What does the "get" do here?

2021-09-16 06:34 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        return newMajor || newMinor || newPatch;
Why are you checking that e.g. the new Major version is the same for newMinor and newPatch? The function is only checking if a number changed. This information is squashed with the return statement.
In fact why are the strings deconstructed and then compared? Maybe the version string can just be compared?
This would skip a bit of complexity.
(if the version is in a different format, both ways would not work anyway)

2021-09-16 06:34 UTC, brianjahnke commented on src/test/java/io/dataspaceconnector/service/ProjectInformationServiceTest.java
> +public class ProjectInformationServiceTest {
Can the scope be further narrowed down, maybe without SpringBootTest? This loads the complete DSC.

2021-09-16 06:34 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
> +            return ResponseEntity.badRequest().body("Failed to determine if a project"
will change

2021-09-16 06:42 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +            response = new ResponseEntity<>(latestData.toString(), HttpStatus.OK);
@tmberthold What if the response gets an extra boolean field "updateAvailable" and then the always returns with 200? I believe this would simplify the endpoint a bit. Just wondering what would be the best way for users of the endpoint?

2021-09-16 06:44 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        return newMajor || newMinor || newPatch;
We wanted to make sure that a new release is actually a newer release based on its version number. With the solution we are on the safe side, but can be simplified to String-compare.

2021-09-16 06:46 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +            response = new ResponseEntity<>(latestData.toString(), HttpStatus.OK);
Can do that, the UI would have to check for this flag first instead of the status code if there is an update.

2021-09-16 06:49 UTC, brianjahnke commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        return newMajor || newMinor || newPatch;
I agree, the current solution is superior. Its just not used. Otherwise somemore information could be feedback? Like "It's safe to upgrade, is just a bugfix"?

2021-09-16 06:51 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        return newMajor || newMinor || newPatch;
I'll think of something, maybe we can give that to the UI as info what kind of update it is.

2021-09-16 07:20 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
> +    @Hidden
endpoint should not be hidden

2021-09-16 07:37 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
> +    @Hidden
needs to be added to openapi.yaml if not hidden

2021-09-16 08:21 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        builder.get();
The HTTP request itself is built by the builder, the get() sets the HTTP request type to GET. For example post() is also possible to perform an HTTP-POST "request".

2021-09-16 09:13 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/controller/gui/GuiController.java
> +    @Hidden
https://springhow.com/spring-boot-actuator-info-endpoint/

2021-09-16 09:21 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +        return newMajor || newMinor || newPatch;
adeed an enum to reflect the type of update or NO_UPDATE and added it to the API output https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/581/commits/1fd03e20f8523a60d5e4be1750420a80f28f7f45

2021-09-16 11:27 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/service/ProjectInformationService.java
> +            response = new ResponseEntity<>(latestData.toString(), HttpStatus.OK);
- enum as flag, if MAJOR, MINOR, PATCH or NO_UPDATE
- moved ResponseEntity Builder to Controller

2021-09-16 15:02 UTC, tmberthold commented
![image](https://user-images.githubusercontent.com/75306992/133636423-71201750-63a1-42fe-95dd-2cc14aa23e97.png)

2021-09-17 06:18 UTC, tmberthold commented
![image](https://user-images.githubusercontent.com/75306992/133733954-6ae5c1dc-5194-4e40-b99b-7406844e555e.png)

2021-09-17 10:37 UTC, vdakker commented on src/test/java/io/dataspaceconnector/service/ProjectInformationServiceTest.java
> +public class ProjectInformationServiceTest {
ProjectInformationServiceTest now mocks dependencies instead of using the whole Spring Context.

2021-09-20 06:23 UTC, brianjahnke approved these changes

2021-09-20 06:27 UTC, merged