Basic policy negotiation
FraunhoferISST/DataspaceConnector pull request #80
Opened 2021-01-03 23:34 UTC by juliapampus

I added some open ToDos and will create some issues for the IDS Framework. The basic contract negotiation works.

Closes issue #3, #5, and #49.

2021-01-03 23:42 UTC, juliapampus commented
`Error:  Tests run: 15, Failures: 3, Errors: 5, Skipped: 0` Should we delete the failing tests for now? @brianjahnke

2021-01-04 13:02 UTC, brianjahnke requested changes
Some small changes (see comments). The test cases are a problem that needs to be addressed asap.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/exceptions/resource/InvalidResourceException.java
> +     * Construct a InvalidResourceException with the specified detail message and cause.
Im not sure that is correct. I am pretty sure the "an" was correct.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/exceptions/resource/InvalidResourceException.java
> +     * Construct a InvalidResourceException with the specified detail message and cause.
Im not sure that is correct. I am pretty sure the "an" was correct.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/exceptions/resource/InvalidResourceException.java
> +     * Construct a InvalidResourceException with the specified detail cause.
Im not sure that is correct. I am pretty sure the "an" was correct.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/filter/httptracing/HttpTraceEventHandler.java
> +        LOGGER.trace("{}", trace);
Are you sure this should be pushed? It seems to be a local (debug) change.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/filter/httptracing/HttpTraceEventHandler.java
> +     * Raise an HttpTraceEvent.
The "an" is wrong. Otherwise why did you remove the "an" in ResourceNotFoundException?

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/filter/httptracing/HttpTraceFilter.java
> +//@Component
This was a hotfix for the broken http tracer. It should not be pushes.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/model/ResourceContract.java
> +    public UUID getId() {
@Data automatilly adds getter and setter

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/NegotiationService.java
> +                }
Why is all this dead code here? (Ignore if answered by the TODO)

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/RequestService.java
> +            LOGGER.warn("Message could not be built. " + e.getMessage());
A different syntax is used for the logging. Use {} instead of +.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/RequestService.java
> +            LOGGER.warn("Message could not be built. " + e.getMessage());
A different syntax is used for the logging. Use {} instead of +.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/ResponseService.java
> +        for (String version : connector.getInboundModelVersion()) {
Could be var.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/handler/NotificationMessageHandler.java
> +    private final Connector connector;
Im not sure the connector can be stored locally since the connector maybe updated in the configcontainer and the pointer here will not be updated.

2021-01-04 13:02 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/response/DescriptionResponseService.java
> +            List<String> keywords = new ArrayList<>();
Could be var

2021-01-04 13:02 UTC, brianjahnke commented on src/main/resources/log4j2.xml
> +        <Logger name="de.fraunhofer.isst.dataspaceconnector" level="debug">
Should be "info"

2021-01-05 12:08 UTC, brianjahnke requested changes
Nothing big. Maybe update the branch with the dev branch before merging so that the merge mistakes are happening on this branch?

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/RequestService.java
> +            LOGGER.warn("Message could not be built. {}", e.getMessage());
Still not correct. Should be [exception=({})]

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/handler/ArtifactMessageHandler.java
> +        this.connector = configurationContainer.getConnector();
That does not fix the problem. You should store the configcontainer.

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/handler/ContractMessageHandler.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/handler/DescriptionMessageHandler.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/handler/NotificationMessageHandler.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/notification/LogMessageService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/notification/NotificationMessageService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/request/ArtifactRequestService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/request/ContractRequestService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/response/ArtifactResponseService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/response/ContractResponseService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-05 12:08 UTC, brianjahnke commented on src/main/java/de/fraunhofer/isst/dataspaceconnector/services/messages/response/DescriptionResponseService.java
> +        this.connector = configurationContainer.getConnector();
See ArtifactMessageHandler

2021-01-14 08:19 UTC, brianjahnke approved these changes, later dismissed

2021-01-14 08:24 UTC, brianjahnke approved these changes

2021-01-14 08:31 UTC, merged