chore: extend enum endpoint
FraunhoferISST/DataspaceConnector pull request #848
Opened 2022-01-20 10:03 UTC by juliapampus

2022-01-20 10:25 UTC, tmberthold commented on src/main/java/io/dataspaceconnector/controller/gui/util/GuiUtils.java
> -                    put("displayName", PaymentMethod.class.getField(paymentMethod.name())
I am not sure if removing the JsonProperty-content might not cause problems. I think that the PUT and POST APIs from GUI to DSC need it in the JSON.

e.g. 
@JsonProperty("**fixedPrice**")
FIXED_PRICE("Fixed price")

With the adjustment only the two lower enum-name/value would be output `FIXED_PRICE` (by paymentMethod.name() as originalName) and `Fixed price` (by paymentMethod.toString() as displayName) but not `fixedPrice`. Same for negotiationBasis. 

I could be wrong, didn't runtime test it.

2022-01-20 11:42 UTC, brianjahnke requested changes
Hi,
- The test coverage does not seem high enough
- The openapi yaml needs an update
- Not all changes are documented in the changelog?

2022-01-20 12:42 UTC, juliapampus commented
> Hi,
> 
> * The test coverage does not seem high enough
> * The openapi yaml needs an update
> * Not all changes are documented in the changelog?

OpenApi will be changed anyway in PR #838. What changes are not in the `CHANGELOG.md`?

2022-01-20 13:17 UTC, brianjahnke commented
Hi,
`Not all changes are documented in the changelog?`

I think the enums changed to some string. For example MY_DATA to MyData.
I was not sure if this needs to be documented there the `?`.

2022-01-20 14:10 UTC, brianjahnke submitted a review, later dismissed

2022-01-20 14:10 UTC, tmberthold commented
wait for me, still checking something

2022-01-20 14:21 UTC, brianjahnke commented
ok :suspect:

2022-01-20 14:55 UTC, brianjahnke approved these changes

2022-01-21 07:12 UTC, tmberthold approved these changes

2022-01-21 07:27 UTC, merged